/* COMPATIBILITY
   - HLSL compilers (untested)
   - Cg compilers
*/

/*
   Author: Gigaherz
   License: Public domain
*/

void main (
    float3 aPosition, 
    float2 aTexcoord, 
    uniform float4x4 wvp,
    uniform float2 texture_size,
    out float4 vPosition : POSITION,
    out float2 vTexcoord : TEXCOORD0,
    out float2 omega : TEXCOORD1
    )
{
    vPosition = mul(float4(aPosition, 1.f),wvp);
    vTexcoord = aTexcoord;
    omega = 3.141592654 * 2 * texture_size;
}
